# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6092d8268aae71b7e6907e7680981b33a3e6ad92da26852f790644b8b1f172a412bd4a681b0fa78d6ec6fb8effcdca384b224d16b1c2e0d35a4d3c5ba77507ac

test:
  secret_key_base: e10610e6c2f036a9ccaaae5f52b22c136e0a439502dd080d40f18fdf6c181e426adb6e6a3d17de7fab4d166575f0313fc7f715f9cd2dca5a445e20af602f933f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
